import { useState } from 'react';
import { sectionDefinition } from './sectionRegistry';

const input = 'mt-1 w-full rounded-xl border border-stone-200 p-3 text-sm outline-none focus:border-stone-900';
function Group({ title, children, defaultOpen = true }: { title: string; children: React.ReactNode; defaultOpen?: boolean }) { const [open, setOpen] = useState(defaultOpen); return <section className="border-b"><button type="button" className="flex w-full items-center justify-between px-5 py-4 text-left text-xs font-bold uppercase tracking-widest" onClick={() => setOpen(!open)} aria-expanded={open}>{title}<span aria-hidden>{open ? '−' : '+'}</span></button>{open && <div className="space-y-4 px-5 pb-5">{children}</div>}</section>; }
function Field({ label, value, onChange, type = 'text', hint, testId }: { label: string; value: any; onChange: (value: string) => void; type?: string; hint?: string; testId?: string }) { return <label className="block text-sm font-semibold">{label}<input data-testid={testId} className={input} type={type} value={value ?? ''} onChange={(event) => onChange(event.target.value)} />{hint && <span className="mt-1 block text-xs font-normal text-stone-500">{hint}</span>}</label>; }
export default function BuilderInspector({ business, selected, onChange }: { business: any; selected: string; onChange: (patch: Record<string, unknown>) => void }) {
  const definition = sectionDefinition(selected); const cta = business.cta || {};
  return <aside data-testid="builder-inspector" className="h-full overflow-auto bg-white"><header className="border-b p-5"><p className="text-xs font-bold uppercase tracking-widest text-stone-500">Estás editando</p><h2 className="text-xl font-bold">{definition?.label || 'Diseño'}</h2></header>
    {(selected === 'HERO' || selected === 'ABOUT') && <Group title="Contenido"><Field testId={selected === 'HERO' ? 'builder-name-input' : undefined} label={selected === 'HERO' ? 'Título' : 'Encabezado'} value={selected === 'HERO' ? business.name : business.aboutTitle} onChange={(value) => onChange(selected === 'HERO' ? { name: value } : { aboutTitle: value })} /><Field label="Descripción" value={business.description} onChange={(description) => onChange({ description })} /><Field label="Imagen" value={business.cover} type="url" onChange={(cover) => onChange({ cover })} /></Group>}
    {selected === 'HERO' && <><Group title="Llamadas a la acción"><Field label="Botón principal" value={cta.primaryLabel} onChange={(primaryLabel) => onChange({ cta: { ...cta, primaryLabel } })} /><Field label="Acción" value={cta.primaryAction} onChange={(primaryAction) => onChange({ cta: { ...cta, primaryAction } })} hint="WHATSAPP, CONTACT o URL." /><Field label="Botón secundario" value={cta.secondaryLabel} onChange={(secondaryLabel) => onChange({ cta: { ...cta, secondaryLabel } })} /></Group><Group title="Diseño" defaultOpen={false}><Field label="Alineación" value={cta.alignment || 'left'} onChange={(alignment) => onChange({ cta: { ...cta, alignment } })} /><Field label="Altura" value={cta.height || 'medium'} onChange={(height) => onChange({ cta: { ...cta, height } })} /></Group></>}
    {selected === 'CTA' && <Group title="Llamado a la acción"><Field label="Título" value={cta.title || business.name} onChange={(title) => onChange({ cta: { ...cta, title } })} /><Field label="Descripción" value={cta.description} onChange={(description) => onChange({ cta: { ...cta, description } })} /><Field label="Texto del botón" value={cta.primaryLabel} onChange={(primaryLabel) => onChange({ cta: { ...cta, primaryLabel } })} /><Field label="Acción" value={cta.primaryAction} onChange={(primaryAction) => onChange({ cta: { ...cta, primaryAction } })} /></Group>}
    {['CONTACT', 'WHATSAPP', 'MAP', 'FOOTER'].includes(selected) && <Group title="Contacto"><Field label="Teléfono" value={business.phone} type="tel" onChange={(phone) => onChange({ phone })} /><Field label="WhatsApp" value={business.whatsapp} type="tel" onChange={(whatsapp) => onChange({ whatsapp })} /><Field label="Correo electrónico" value={business.email} type="email" onChange={(email) => onChange({ email })} /><Field label="Dirección" value={business.address} onChange={(address) => onChange({ address })} /><Field label="Ciudad" value={business.city} onChange={(city) => onChange({ city })} /><Field label="Referencia de ubicación" value={business.mapsUrl} type="url" onChange={(mapsUrl) => onChange({ mapsUrl })} /></Group>}
    <SocialFields business={business} selected={selected} onChange={onChange} /><HoursFields business={business} selected={selected} onChange={onChange} />
    {selected === 'SEO' && <Group title="Posicionamiento"><Field label="Título SEO" value={business.seoTitle} onChange={(seoTitle) => onChange({ seoTitle })} hint={`${String(business.seoTitle || '').length} de 60 caracteres`} /><Field label="Descripción SEO" value={business.seoDescription} onChange={(seoDescription) => onChange({ seoDescription })} hint={`${String(business.seoDescription || '').length} de 160 caracteres`} /><Field label="Dirección de la página" value={business.slug} onChange={(slug) => onChange({ slug })} /><Field label="Imagen social" value={business.ogImage} type="url" onChange={(ogImage) => onChange({ ogImage })} /></Group>}
    {['SERVICES', 'PRODUCTS', 'CATALOG', 'GALLERY', 'TEAM', 'TESTIMONIALS', 'FAQ'].includes(selected) && <Group title="Contenido"><p className="text-sm leading-6 text-stone-600">Usa únicamente el contenido real de tu negocio.{dataEmpty(selected)}</p></Group>}
  </aside>;
function SocialFields({ business, selected, onChange }: any) { if (!['SOCIALS', 'FOOTER', 'CONTACT'].includes(selected)) return null; const set = (key: string, value: string) => onChange({ socials: { ...business.socials, [key]: value } }); return <Group title="Redes sociales"><Field label="Instagram" value={business.socials?.instagram} onChange={(value) => set('instagram', value)} /><Field label="Facebook" value={business.socials?.facebook} onChange={(value) => set('facebook', value)} /><Field label="TikTok" value={business.socials?.tiktok} onChange={(value) => set('tiktok', value)} /><Field label="YouTube" value={business.socials?.youtube} onChange={(value) => set('youtube', value)} /><Field label="Sitio web" value={business.socials?.website} onChange={(value) => set('website', value)} /></Group>; }
function HoursFields({ business, selected, onChange }: any) { if (selected !== 'OPENING_HOURS') return null; const days = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']; const set = (day: string, value: string) => onChange({ hours: { ...business.hours, [day]: value } }); return <Group title="Horarios">{days.map((day) => <Field key={day} label={day} value={business.hours?.[day]} onChange={(value) => set(day, value)} hint="Ejemplo: 09:00 - 18:00" />)}</Group>; }

}
function dataEmpty(id: string) { return ` No agregaremos ${id === 'FAQ' ? 'preguntas' : 'información'} automáticamente.`; }
