export const CATEGORY_FIXTURES = {
 FOOD: { name: 'Cocina Demo', category: 'FOOD', cta: 'Pedir', modules: ['HERO','CATALOG','PRODUCTS','DELIVERY','PROMOTIONS','HOURS','WHATSAPP','MAP','CONTACT'], sample: { product: { id: 'food-1', name: 'Menú del día', price: 8900 } } },
 BOUTIQUE: { name: 'Boutique Demo', category: 'BOUTIQUE', cta: 'Ver catálogo', modules: ['HERO','CATALOG','PRODUCTS','GALLERY','PROMOTIONS','SOCIALS','WHATSAPP','CONTACT'], sample: { product: { id: 'boutique-1', name: 'Colección demo', price: 19900 } } },
 FURNITURE: { name: 'Muebles Demo', category: 'FURNITURE', cta: 'Cotizar', modules: ['HERO','CATALOG','GALLERY','PORTFOLIO','TEAM','TESTIMONIALS','CONTACT'], sample: { product: { id: 'furniture-1', name: 'Proyecto demo', price: 350000 } } },
 MECHANIC: { name: 'Taller Demo', category: 'MECHANIC', cta: 'Agendar', modules: ['HERO','SERVICES','BRANDS','BEFORE_AFTER','TESTIMONIALS','BOOKING','MAP','HOURS'], sample: { service: { id: 'mechanic-1', name: 'Revisión general', price: 25000 } } },
 PHONE: { name: 'Phone Demo', category: 'PHONE', cta: 'Cotizar reparación', modules: ['HERO','PRODUCTS','SERVICES','REPAIR','BRANDS','MAP','WHATSAPP','CONTACT'], sample: { product: { id: 'phone-1', name: 'Accesorio demo', price: 9900 } } },
 CLEANING: { name: 'Limpieza Demo', category: 'CLEANING', cta: 'Cotizar servicio', modules: ['HERO','SERVICES','PRICING','FEATURES','TESTIMONIALS','BOOKING','MAP'], sample: { service: { id: 'cleaning-1', name: 'Limpieza integral', price: 45000 } } },
 PHOTO: { name: 'Foto Demo', category: 'PHOTO', cta: 'Agendar sesión', modules: ['HERO','PORTFOLIO','GALLERY','SERVICES','PRICING','TESTIMONIALS','BOOKING','SOCIALS'], sample: { service: { id: 'photo-1', name: 'Sesión retrato', price: 60000 } } },
 TUTORING: { name: 'Academia Demo', category: 'TUTORING', cta: 'Agendar clase', modules: ['HERO','SUBJECTS','SERVICES','TEAM','PRICING','TESTIMONIALS','BOOKING','CONTACT'], sample: { service: { id: 'tutoring-1', name: 'Clase particular', price: 20000 } } },
 CONSTRUCTION: { name: 'Construcción Demo', category: 'CONSTRUCTION', cta: 'Solicitar cotización', modules: ['HERO','SERVICES','PORTFOLIO','GALLERY','TEAM','TESTIMONIALS','MAP','CONTACT'], sample: { service: { id: 'construction-1', name: 'Proyecto demo', price: 1200000 } } },
 BEAUTY: { name: 'Belleza Demo', category: 'BEAUTY', cta: 'Agendar', modules: ['HERO','SERVICES','PRICING','TEAM','GALLERY','TESTIMONIALS','BOOKING','PROMOTIONS','WHATSAPP'], sample: { service: { id: 'beauty-1', name: 'Treatment demo', price: 30000 } } },
 PET: { name: 'Pet Demo', category: 'PET', cta: 'Agendar', modules: ['HERO','SERVICES','PRODUCTS','GALLERY','BOOKING','TESTIMONIALS','MAP'], sample: { service: { id: 'pet-1', name: 'Grooming', price: 28000 } } },
 DETAILING: { name: 'Detailing Demo', category: 'DETAILING', cta: 'Agendar servicio', modules: ['HERO','SERVICES','PRICING','BEFORE_AFTER','GALLERY','PROMOTIONS','BOOKING','MAP'], sample: { service: { id: 'detailing-1', name: 'Lavado premium', price: 35000 } } },
} as const;
