import { buildWaLink } from '@/services/business';
import { categoryLabel, ctaLabel } from './businessLabels';
import { thematicAssets } from './assets';
import { BusinessButton, BusinessCard, BusinessContainer, BusinessGallery, BusinessHeading, BusinessImage, BusinessSection } from './components';
import { ContactSection, HoursSection, LocationSection } from './components/BusinessSections';
import type { TemplateProps } from './registry';

const money = (value: any) => value == null ? 'Consultar' : `$${Number(value).toLocaleString('es-CL')}`;
const imageOf = (item: any) => item?.image || item?.images?.[0]?.url || item?.url;
function Cards({ items, dark = false }: { items: any[]; dark?: boolean }) { if (!items?.length) return null; return <div className="grid gap-4 md:grid-cols-3">{items.slice(0, 6).map((item) => <BusinessCard key={item.id} className={dark ? 'border-white/15 bg-white/5 text-white' : ''}>{imageOf(item) && <BusinessImage src={imageOf(item)} alt={item.name || item.title} className="mb-4 aspect-[4/3] w-full rounded-xl object-cover" />}<h3 className="text-lg font-bold">{item.name || item.title}</h3><p className="mt-2 line-clamp-2 text-sm opacity-70">{item.shortDescription || item.description || item.bio}</p><p className="mt-4 font-bold">{money(item.price ?? item.salePrice)}</p></BusinessCard>)}</div>; }
function Hero({ business, image, kicker, title, action, href, dark = false }: any) { return <section id="inicio" className={`relative isolate min-h-[68vh] overflow-hidden ${dark ? 'text-white' : ''}`}><BusinessImage src={image?.src} alt={image?.alt} eager className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className={`absolute inset-0 -z-10 ${dark ? 'bg-gradient-to-r from-black via-black/75 to-black/25' : 'bg-gradient-to-r from-black/70 via-black/40 to-black/10'}`} /><BusinessContainer className="flex min-h-[68vh] items-end py-14"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.32em]">{kicker}</p><h1 className="mt-4 text-5xl font-black leading-[.95] sm:text-7xl" style={{ fontFamily: 'var(--biz-heading)' }}>{business.name}</h1><p className="mt-5 max-w-2xl text-lg opacity-85">{title || business.description}</p><div className="mt-7 flex flex-wrap gap-3"><BusinessButton href={href}>{action}</BusinessButton>{business.phone && <BusinessButton href={`tel:${business.phone}`} variant="secondary">Llamar</BusinessButton>}</div></div></BusinessContainer></section>; }
function GalleryBlock({ business: _business, gallery }: { business: any; gallery: any[] }) { if (!gallery.length) return null; return <BusinessSection className="bg-stone-100"><BusinessContainer><BusinessHeading title="Galería" /><BusinessGallery images={gallery.map((g) => ({ id: g.id, url: g.url, alt: g.alt }))} /></BusinessContainer></BusinessSection>; }
function FooterModules({ business }: { business: any }) { return <><HoursSection business={business} /><LocationSection business={business} /><ContactSection business={business} preview={Boolean(business.__preview)} /></>; }


export default function IndustryTemplate({ business: sourceBusiness, services = [], products = [], gallery = [], testimonials = [], team = [], promotions = [], preview }: TemplateProps) {
  const business = { ...sourceBusiness, __preview: preview };
  const code = String(business?.template?.code || '').toUpperCase();
  const category = String(business?.category || '').toUpperCase();
  const asset = business.cover ? { src: business.cover, alt: `Imagen principal de ${business.name}` } : thematicAssets(category)[0];
  const action = ctaLabel(category);
  const waHref = buildWaLink(business.whatsapp, `Hola ${business.name}, quiero ${action.toLowerCase()}.`);
  const primaryHref = business.whatsapp ? waHref : business.phone ? `tel:${business.phone}` : '#contacto';
  const heroProps = { business, image: asset, action, href: primaryHref };
  if (code === 'CAFE_01' || category === 'CAFE') return <><Hero {...heroProps} kicker="Café de especialidad" title="Tu momento empieza con un buen café." /><BusinessSection id="catalogo" className="bg-[#efe2d1]"><BusinessContainer><BusinessHeading title="Nuestro menú" /><div className="grid gap-6 md:grid-cols-[.7fr_1.3fr]"><p className="rounded-[40px] bg-white/50 p-8 text-xl leading-relaxed">Café preparado con cuidado, lugares para conversar y algo dulce para acompañar.</p><Cards items={products} /></div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'FOOD_01' || category === 'FOOD') return <><Hero {...heroProps} kicker="Gastronomía" title="Una experiencia para disfrutar." dark /><BusinessSection id="catalogo" className="bg-stone-100"><BusinessContainer><BusinessHeading title="Menú y platos destacados" /><Cards items={products} /></BusinessContainer></BusinessSection>{promotions.length > 0 && <BusinessSection className="bg-[var(--biz-accent)] text-white"><BusinessContainer><BusinessHeading title={promotions[0].title} text={promotions[0].description} /><BusinessButton href={primaryHref}>Reservar mesa</BusinessButton></BusinessContainer></BusinessSection>}<GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'NAILS_01' || category === 'NAILS') return <><Hero {...heroProps} kicker="Uñas y cuidado" title="Detalles que reflejan tu estilo." /><BusinessSection className="bg-[#f7eeee]"><BusinessContainer><BusinessHeading title="Nuestros servicios" /><div className="grid gap-4 sm:grid-cols-2">{services.map((item) => <BusinessCard key={item.id} className="border-rose-200"><h3 className="font-serif text-2xl">{item.name}</h3><p className="mt-2 text-sm opacity-70">{item.description}</p><b className="mt-5 block">{money(item.price)}</b></BusinessCard>)}</div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'PETS_01' || category === 'PET') return <><Hero {...heroProps} kicker="Mascotas" title="Cariño y cuidado para quienes son familia." /><BusinessSection className="bg-[#edf8f4]"><BusinessContainer><BusinessHeading title="Cuidado con cariño" /><Cards items={services} /></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'FITNESS_01') return <><Hero {...heroProps} kicker="Gimnasio y fitness" title="Supera tu próxima meta." dark /><BusinessSection className="bg-[#f2f4f5]"><BusinessContainer><div className="mb-8 flex items-end justify-between"><BusinessHeading title="Planes y entrenamiento" /><b className="text-5xl text-[var(--biz-accent)]">MOVE</b></div><Cards items={products.length ? products : services} /></BusinessContainer></BusinessSection><BusinessSection className="bg-black text-white"><BusinessContainer><BusinessHeading title="Entrenadores" /><div className="grid gap-4 md:grid-cols-3">{team.map((item: any) => <BusinessCard key={item.id} className="border-white/10 bg-white/5 text-white"><b>{item.name}</b><p className="text-sm opacity-70">{item.role || item.position}</p></BusinessCard>)}</div></BusinessContainer></BusinessSection><FooterModules business={business} /></>;
  if (code === 'AUTO_01' || category === 'MECHANIC' || category === 'DETAILING') return <><Hero {...heroProps} kicker="Automotriz" title="Cuidado técnico para moverte con confianza." dark /><BusinessSection className="bg-stone-100"><BusinessContainer><BusinessHeading title="Servicios" /><div className="divide-y border-y">{services.map((item) => <div key={item.id} className="grid gap-2 py-5 sm:grid-cols-[1fr_auto]"><div><b>{item.name}</b><p className="text-sm opacity-70">{item.description}</p></div><b>{money(item.price)}</b></div>)}</div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'PRO_01' || category === 'PRO' || category === 'CONSTRUCTION') return <><Hero {...heroProps} kicker="Servicios profesionales" title="Experiencia, claridad y resultados." /><BusinessSection><BusinessContainer><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><BusinessHeading title="Cómo te ayudamos" /><p className="opacity-70">Un proceso claro, comunicación directa y un equipo que resuelve.</p></div><Cards items={services} /></div></BusinessContainer></BusinessSection>{testimonials.length > 0 && <BusinessSection className="bg-stone-100"><BusinessContainer><BusinessHeading title="Confianza de nuestros clientes" /><div className="grid gap-4 md:grid-cols-2">{testimonials.map((item: any) => <blockquote key={item.id} className="rounded-2xl bg-white p-6 text-lg">“{item.quote || item.content}”<footer className="mt-3 text-sm opacity-60">— {item.name}</footer></blockquote>)}</div></BusinessContainer></BusinessSection>}<FooterModules business={business} /></>;
  return <><Hero {...heroProps} kicker={categoryLabel(category)} title={business.description} /><BusinessSection><BusinessContainer><BusinessHeading title={category === 'PHOTO' ? 'Portafolio' : 'Nuestros servicios'} /><Cards items={products.length ? products : services} /></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
}
