import { buildWaLink } from '@/services/business';
import { categoryLabel } from './businessLabels';
import { getIndustryComposition, type IndustryComposition } from './industryComposition';
import { thematicAssets } from './assets';
import { BusinessButton, BusinessCard, BusinessContainer, BusinessGallery, BusinessHeading, BusinessImage, BusinessSection } from './components';
import { ContactSection, HoursSection, LocationSection } from './components/BusinessSections';
import type { TemplateProps } from './registry';

const money = (value: any) => value == null ? 'Consultar' : `$${Number(value).toLocaleString('es-CL')}`;
const imageOf = (item: any) => item?.image || item?.images?.[0]?.url || item?.url;
function Cards({ items, dark = false, composition }: { items: any[]; dark?: boolean; composition?: IndustryComposition }) { if (!items?.length) return null; const grid = composition?.layout === 'masonry' ? 'columns-1 sm:columns-2 lg:columns-3' : composition?.layout === 'service' ? 'grid gap-3 md:grid-cols-2' : 'grid gap-4 md:grid-cols-3'; return <div className={grid}>{items.slice(0, 8).map((item) => <BusinessCard key={item.id} className={`${dark ? 'border-white/15 bg-white/5 text-white' : composition?.cards === 'image-first' ? 'border-0 bg-transparent p-0 shadow-none' : ''} break-inside-avoid mb-4`}>{imageOf(item) && <BusinessImage src={imageOf(item)} alt={item.name || item.title} className={`mb-4 w-full object-cover ${composition?.imageTreatment === 'portrait' ? 'aspect-[3/4]' : composition?.imageTreatment === 'masonry' ? 'aspect-auto' : 'aspect-[4/3]'} ${composition?.cards === 'image-first' ? 'rounded-[var(--biz-radius)]' : 'rounded-xl'}`} />}<h3 className="text-lg font-bold">{item.name || item.title}</h3><p className="mt-2 line-clamp-2 text-sm opacity-70">{item.shortDescription || item.description || item.bio}</p><p className="mt-4 font-bold">{money(item.price ?? item.salePrice)}</p></BusinessCard>)}</div>; }
function Hero({ business, image, kicker, title, action, href, dark = false, composition }: { business: any; image?: any; kicker: string; title?: string; action: string; href: string; dark?: boolean; composition: IndustryComposition }) { const portrait = composition.hero === 'architectural' || composition.hero === 'portfolio' || composition.hero === 'wellness'; return <section id="inicio" className={`relative isolate min-h-[68vh] overflow-hidden text-white ${dark ? 'text-white' : ''} ${composition.hero === 'editorial' ? 'lg:min-h-[76vh]' : ''}`}><BusinessImage src={image?.src} alt={image?.alt || `Imagen principal de ${business.name}`} eager className={`absolute inset-0 -z-20 h-full w-full object-cover ${composition.imageTreatment === 'portrait' ? 'object-[center_35%]' : ''}`} /><div className={`absolute inset-0 -z-10 ${dark || composition.hero === 'cinematic' ? 'bg-gradient-to-r from-black via-black/75 to-black/25' : composition.hero === 'photography' ? 'bg-gradient-to-t from-black/80 via-black/35 to-black/10' : 'bg-gradient-to-r from-black/70 via-black/35 to-black/5'}`} /><BusinessContainer className={`flex min-h-[68vh] items-end py-14 ${portrait ? 'sm:items-center sm:py-24' : ''}`}><div className={`max-w-3xl ${composition.hero === 'architectural' ? 'ml-auto text-right' : ''}`}><p className="text-xs font-bold uppercase tracking-[.32em]">{kicker}</p><h1 className="mt-4 text-5xl font-black leading-[.95] sm:text-7xl" style={{ fontFamily: 'var(--biz-heading)' }}>{business.name}</h1><p className="mt-5 max-w-2xl text-lg opacity-85">{title || business.description}</p><div className="mt-7 flex flex-wrap gap-3"><BusinessButton href={href}>{action}</BusinessButton>{business.phone && <BusinessButton href={`tel:${business.phone}`} variant="secondary">Llamar</BusinessButton>}</div></div></BusinessContainer></section>; }
function GalleryBlock({ business: _business, gallery }: { business: any; gallery: any[] }) { if (!gallery.length) return null; return <BusinessSection className="bg-stone-100"><BusinessContainer><BusinessHeading title="Galería" /><BusinessGallery images={gallery.map((g) => ({ id: g.id, url: g.url, alt: g.alt }))} /></BusinessContainer></BusinessSection>; }
function FooterModules({ business }: { business: any }) { return <><HoursSection business={business} /><LocationSection business={business} /><ContactSection business={business} preview={Boolean(business.__preview)} /></>; }


export default function IndustryTemplate({ business: sourceBusiness, services = [], products = [], gallery = [], testimonials = [], team = [], promotions = [], preview }: TemplateProps) {
  const business = { ...sourceBusiness, __preview: preview };
  const code = String(business?.template?.code || '').toUpperCase();
  const category = String(business?.category || '').toUpperCase();
  const composition = getIndustryComposition(code, category);
  const asset = business.cover ? { src: business.cover, alt: `Imagen principal de ${business.name}` } : thematicAssets(category)[0];
  const action = composition.cta;
  const waHref = buildWaLink(business.whatsapp, `Hola ${business.name}, quiero ${action.toLowerCase()}.`);
  const primaryHref = business.whatsapp ? waHref : business.phone ? `tel:${business.phone}` : '#contacto';
  const heroProps = { business, image: asset, action, href: primaryHref, composition };
  if (code === 'BEAUTY_01' || category === 'BEAUTY') return <><Hero {...heroProps} kicker="Beauty & bienestar" title="Rituales de calma, cuidado y belleza." dark /><BusinessSection id="servicios" className="bg-[#f3ebe7]"><BusinessContainer><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><BusinessHeading title="Tratamientos Signature" text="Experiencias personalizadas para piel, cuerpo y bienestar." /><div className="grid gap-4 sm:grid-cols-2">{services.map((item) => <BusinessCard key={item.id} className="overflow-hidden border-[#dfc8bd] bg-white p-0"><BusinessImage src={item.image} alt={item.name} className="aspect-[4/3] w-full object-cover" /><div className="p-6"><p className="text-xs uppercase tracking-[.22em] text-[#9b6b5b]">Experiencia wellness</p><h3 className="mt-2 font-serif text-2xl">{item.name}</h3><p className="mt-2 text-sm opacity-70">{item.description}</p><b className="mt-5 block">{money(item.price)}</b></div></BusinessCard>)}</div></div></BusinessContainer></BusinessSection><BusinessSection id="galeria" className="bg-white"><BusinessContainer><BusinessHeading title="Rituales que renuevan" /><BusinessGallery images={gallery.map((item) => ({ id: item.id, url: item.url, alt: item.alt }))} className="md:grid-cols-4" /></BusinessContainer></BusinessSection><FooterModules business={business} /></>;
  if (code === 'BAKERY_01' || category === 'BAKERY') return <><Hero {...heroProps} kicker="Panadería artesanal" title="Horneado cada mañana, para endulzar el día." dark /><BusinessSection id="catalogo" className="bg-[#f5e4cb]"><BusinessContainer><div className="grid gap-10 md:grid-cols-[1.2fr_.8fr]"><Cards composition={composition} items={products} /><div className="rounded-[2rem] bg-[#8a4f2d] p-8 text-[#fff8ed]"><p className="text-xs uppercase tracking-[.25em] text-amber-100">Nuestro horno</p><h2 className="mt-3 font-serif text-4xl">Masa lenta. Sabor profundo.</h2><p className="mt-4 leading-relaxed text-amber-50/80">Ingredientes simples, técnica artesanal y frescura diaria.</p></div></div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'BOUTIQUE_01' || category === 'BOUTIQUE') return <><Hero {...heroProps} kicker="Boutique editorial" title="Piezas con carácter para un estilo inconfundible." dark /><BusinessSection id="catalogo" className="bg-[#eee8df]"><BusinessContainer><BusinessHeading title="La colección" /><div className="grid grid-cols-2 gap-x-4 gap-y-8 lg:grid-cols-3">{products.slice(0, 6).map((item) => <article key={item.id} className="group"><BusinessImage src={imageOf(item)} alt={item.name} className="aspect-[3/4] w-full object-cover" /><p className="mt-4 text-lg font-semibold">{item.name}</p><p className="mt-1 text-sm opacity-65">{item.description}</p><b className="mt-3 block">{money(item.salePrice)}</b></article>)}</div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'PHOTO_01' || category === 'PHOTO') return <><Hero {...heroProps} kicker="Estudio fotográfico" title="Historias que merecen ser vistas." dark /><BusinessSection id="galeria" className="bg-neutral-950 text-white"><BusinessContainer><div className="mb-10 flex items-end justify-between"><BusinessHeading title="Proyectos seleccionados" /><span className="text-xs uppercase tracking-[.3em] text-cyan-300">Portafolio</span></div><BusinessGallery images={gallery.map((item) => ({ id: item.id, url: item.url, alt: item.alt }))} className="grid-cols-2 md:grid-cols-3" /></BusinessContainer></BusinessSection><BusinessSection className="bg-stone-100"><BusinessContainer><BusinessHeading title="Servicios de sesión" /><Cards composition={composition} items={services} /></BusinessContainer></BusinessSection><FooterModules business={business} /></>;
  if (code === 'CAFE_01' || category === 'CAFE') return <><Hero {...heroProps} kicker="Café de especialidad" title="Tu momento empieza con un buen café." dark /><BusinessSection id="catalogo" className="bg-[#efe2d1]"><BusinessContainer><BusinessHeading title="Nuestro menú" /><div className="grid gap-6 md:grid-cols-[.7fr_1.3fr]"><p className="rounded-[40px] bg-white/50 p-8 text-xl leading-relaxed">Café preparado con cuidado, lugares para conversar y algo dulce para acompañar.</p><Cards composition={composition} items={products} /></div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'FOOD_01' || category === 'FOOD') return <><Hero {...heroProps} kicker="Gastronomía" title="Una experiencia para disfrutar." dark /><BusinessSection id="catalogo" className="bg-stone-100"><BusinessContainer><BusinessHeading title="Menú y platos destacados" /><Cards composition={composition} items={products} /></BusinessContainer></BusinessSection>{promotions.length > 0 && <BusinessSection className="bg-[var(--biz-accent)] text-white"><BusinessContainer><BusinessHeading title={promotions[0].title} text={promotions[0].description} /><BusinessButton href={primaryHref}>Reservar mesa</BusinessButton></BusinessContainer></BusinessSection>}<GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'NAILS_01' || category === 'NAILS') return <><Hero {...heroProps} kicker="Uñas y cuidado" title="Detalles que reflejan tu estilo." /><BusinessSection className="bg-[#f7eeee]"><BusinessContainer><BusinessHeading title="Nuestros servicios" /><div className="grid gap-4 sm:grid-cols-2">{services.map((item) => <BusinessCard key={item.id} className="border-rose-200"><h3 className="font-serif text-2xl">{item.name}</h3><p className="mt-2 text-sm opacity-70">{item.description}</p><b className="mt-5 block">{money(item.price)}</b></BusinessCard>)}</div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'PETS_01' || category === 'PET') return <><Hero {...heroProps} kicker="Mascotas" title="Cariño y cuidado para quienes son familia." /><BusinessSection className="bg-[#edf8f4]"><BusinessContainer><BusinessHeading title="Cuidado con cariño" /><Cards composition={composition} items={services} /></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'FITNESS_01') return <><Hero {...heroProps} kicker="Gimnasio y fitness" title="Supera tu próxima meta." dark /><BusinessSection className="bg-[#f2f4f5]"><BusinessContainer><div className="mb-8 flex items-end justify-between"><BusinessHeading title="Planes y entrenamiento" /><b className="text-5xl text-[var(--biz-accent)]">MOVE</b></div><Cards composition={composition} items={products.length ? products : services} /></BusinessContainer></BusinessSection><BusinessSection className="bg-black text-white"><BusinessContainer><BusinessHeading title="Entrenadores" /><div className="grid gap-4 md:grid-cols-3">{team.map((item: any) => <BusinessCard key={item.id} className="border-white/10 bg-white/5 text-white"><b>{item.name}</b><p className="text-sm opacity-70">{item.role || item.position}</p></BusinessCard>)}</div></BusinessContainer></BusinessSection><FooterModules business={business} /></>;
  if (code === 'AUTO_01' || category === 'MECHANIC' || category === 'DETAILING') return <><Hero {...heroProps} kicker="Automotriz" title="Cuidado técnico para moverte con confianza." dark /><BusinessSection className="bg-stone-100"><BusinessContainer><BusinessHeading title="Servicios" /><div className="divide-y border-y">{services.map((item) => <div key={item.id} className="grid gap-2 py-5 sm:grid-cols-[1fr_auto]"><div><b>{item.name}</b><p className="text-sm opacity-70">{item.description}</p></div><b>{money(item.price)}</b></div>)}</div></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
  if (code === 'PRO_01' || category === 'PRO' || category === 'CONSTRUCTION') return <><Hero {...heroProps} kicker="Servicios profesionales" title="Experiencia, claridad y resultados." /><BusinessSection><BusinessContainer><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><BusinessHeading title="Cómo te ayudamos" /><p className="opacity-70">Un proceso claro, comunicación directa y un equipo que resuelve.</p></div><Cards composition={composition} items={services} /></div></BusinessContainer></BusinessSection>{testimonials.length > 0 && <BusinessSection className="bg-stone-100"><BusinessContainer><BusinessHeading title="Confianza de nuestros clientes" /><div className="grid gap-4 md:grid-cols-2">{testimonials.map((item: any) => <blockquote key={item.id} className="rounded-2xl bg-white p-6 text-lg">“{item.quote || item.content}”<footer className="mt-3 text-sm opacity-60">— {item.name}</footer></blockquote>)}</div></BusinessContainer></BusinessSection>}<FooterModules business={business} /></>;
  return <><Hero {...heroProps} kicker={categoryLabel(category)} title={business.description} /><BusinessSection><BusinessContainer><BusinessHeading title={category === 'PHOTO' ? 'Portafolio' : 'Nuestros servicios'} /><Cards composition={composition} items={products.length ? products : services} /></BusinessContainer></BusinessSection><GalleryBlock business={business} gallery={gallery} /><FooterModules business={business} /></>;
}
