import { Suspense, useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { getBusiness, getBusinessCapabilities, pauseBusinessPage, publishBusinessPage, saveBusinessCapabilities, updateBusiness, getBusinessContent, listBusinessProducts, listServices } from '@/services/business';
import BusinessPageRenderer from '@/business/BusinessPageRenderer';
import BuilderTopBar from '@/business/builder/BuilderTopBar';
import { BuilderSidebar } from '@/business/builder/BuilderSidebar';
import BuilderInspector from '@/business/builder/BuilderInspector';
import { sectionDefinition } from '@/business/builder/sectionRegistry';
import { useBuilderState } from '@/business/builder/useBuilderState';

export default function BusinessBuilder() {
  const [params] = useSearchParams(); const id = params.get('id') || '';
  const { state, dispatch, changeBusiness, changeSections } = useBuilderState();
  const [content, setContent] = useState<any>({ services: [], products: [], properties: [], gallery: [], testimonials: [], faqs: [], promotions: [], team: [], bookingSlots: [] });
  const [loadError, setLoadError] = useState(''); const [publishError, setPublishError] = useState('');
  const [mobilePanel, setMobilePanel] = useState<'structure' | 'inspector' | null>(null);
  useEffect(() => { if (!id) return; let active = true; void Promise.all([getBusiness(id), getBusinessCapabilities(id), getBusinessContent(id), listBusinessProducts(id), listServices(id)]).then(([business, capabilities, extra, products, services]) => { if (!active) return; dispatch({ type: 'LOAD', business, sections: capabilities.sections || [] }); setContent({ ...extra, products, services, properties: business.properties || [], gallery: business.gallery || [], bookingSlots: [] }); }).catch(() => active && setLoadError('No se pudo cargar la página.')); return () => { active = false; }; }, [id, dispatch]);
  const save = useCallback(async (): Promise<boolean> => { if (!id || !state.business) return false; dispatch({ type: 'SAVE_START' }); try { const business = state.business; const payload = { name: business.name, slug: business.slug, category: business.category, description: business.description || null, phone: business.phone || null, whatsapp: business.whatsapp || null, email: business.email || null, address: business.address || null, city: business.city || null, region: business.region || null, mapsUrl: business.mapsUrl || null, lat: business.lat ?? null, lng: business.lng ?? null, hours: business.hours ?? null, socials: business.socials ?? null, cta: business.cta ?? null, settings: business.settings ?? null, visual: business.visual ?? null, logo: business.logo || null, cover: business.cover || null, seoTitle: business.seoTitle || null, seoDescription: business.seoDescription || null, ogImage: business.ogImage || null, canonical: business.canonical || null }; await Promise.all([updateBusiness(id, payload), saveBusinessCapabilities(id, state.sections)]); dispatch({ type: 'SAVE_DONE' }); return true; } catch { dispatch({ type: 'SAVE_ERROR', error: 'Intenta nuevamente.' }); return false; } }, [id, state.business, state.sections, dispatch]);
  const pick = (sectionId: string) => { const definition = sectionDefinition(sectionId); if (!definition) return; const rendererId = definition.rendererCapability || sectionId; changeSections([...state.sections.filter((section: { id: string }) => section.id !== rendererId), { id: rendererId, enabled: true, order: (state.sections.length + 1) * 10 }]); dispatch({ type: 'SELECT', section: sectionId }); };
  useEffect(() => { if (state.saveState !== 'DIRTY') return; const timer = window.setTimeout(() => { void save(); }, 1500); return () => window.clearTimeout(timer); }, [state.saveState, state.business, state.sections, save]);
  const publish = async () => { if (!id) return; setPublishError(''); try { if (state.saveState === 'DIRTY' || state.saveState === 'ERROR') { const saved = await save(); if (!saved) return; } const result = await publishBusinessPage(id); dispatch({ type: 'LOAD', business: result.business, sections: state.sections }); window.setTimeout(() => window.alert('Cambios publicados correctamente.'), 50); } catch (error: any) { setPublishError(error?.response?.data?.message || 'El backend no permitió publicar la página.'); } };
  const pause = async () => { if (!id || !window.confirm('¿Pausar esta página?')) return; const business = await pauseBusinessPage(id); dispatch({ type: 'LOAD', business, sections: state.sections }); };
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (!(event.ctrlKey || event.metaKey)) return; if (event.key.toLowerCase() === 'z' && !event.shiftKey) { event.preventDefault(); dispatch({ type: 'UNDO' }); } if ((event.key.toLowerCase() === 'z' && event.shiftKey) || event.key.toLowerCase() === 'y') { event.preventDefault(); dispatch({ type: 'REDO' }); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [dispatch]);
  if (!id) return <main className="p-8">Falta seleccionar una página.</main>;
  if (!state.business) return <main className="p-8" aria-busy="true">{loadError || 'Cargando editor…'}</main>;
  const previewBusiness = { ...state.business, visual: { ...state.business.visual, sections: state.sections } };
  return <main data-testid="business-builder" className="min-h-screen bg-stone-100 text-stone-900"><BuilderTopBar business={state.business} saveState={state.saveState} device={state.device} sections={state.sections} canUndo={!!state.history.length} canRedo={!!state.future.length} onDevice={(device: any) => dispatch({ type: 'DEVICE', device })} onUndo={() => dispatch({ type: 'UNDO' })} onRedo={() => dispatch({ type: 'REDO' })} onSave={save} onPublish={publish} onPause={pause} />
    <div className="grid min-h-[calc(100vh-80px)] lg:grid-cols-[270px_minmax(0,1fr)_320px]">
      <div data-testid="builder-sidebar-desktop" className="hidden lg:block"><BuilderSidebar sections={state.sections} selected={state.selectedSection} onSelect={(selectedSection: string) => dispatch({ type: 'SELECT', section: selectedSection })} onChange={changeSections} onPick={pick} /></div>
      <section data-testid="builder-preview" className="min-w-0 p-3 pb-24 sm:p-6 sm:pb-24"><div className="mx-auto mb-4 flex items-center justify-between rounded-2xl bg-white p-3 shadow-sm"><p className="text-sm font-semibold">Tu página, en tiempo real</p><span className="text-xs text-stone-500">{state.device}</span></div><div className={`mx-auto overflow-hidden rounded-2xl bg-white shadow-xl transition-all ${state.device === 'mobile' ? 'max-w-[390px]' : state.device === 'tablet' ? 'max-w-[768px]' : 'max-w-full'}`}><Suspense fallback={<div className="min-h-96 animate-pulse bg-stone-100" />}><BusinessPageRenderer business={previewBusiness} {...content} preview /></Suspense></div></section>
      <div data-testid="builder-inspector-desktop" className="hidden lg:block"><BuilderInspector business={state.business} selected={state.selectedSection} onChange={changeBusiness} /></div>
    </div>
    <div data-testid="builder-mobile-actions" className="fixed z-30 grid grid-cols-2 border-t bg-white p-2 shadow-[0_-8px_30px_rgba(0,0,0,.08)] lg:hidden"><button type="button" onClick={() => setMobilePanel('structure')} className="min-h-12 rounded-xl bg-stone-100 font-semibold">Secciones</button><button type="button" onClick={() => setMobilePanel('inspector')} className="min-h-12 rounded-xl bg-stone-900 font-semibold text-white">Editar</button></div>
    {mobilePanel && <div className="fixed inset-0 z-50 flex items-end bg-stone-950/40 lg:hidden" role="dialog" aria-modal="true" aria-label={mobilePanel === 'structure' ? 'Estructura de la página' : 'Inspector de sección'}><button type="button" aria-label="Cerrar panel" className="absolute inset-0" onClick={() => setMobilePanel(null)} /><div className="relative max-h-[88vh] w-full overflow-hidden rounded-t-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4"><strong>{mobilePanel === 'structure' ? 'Estructura' : 'Inspector'}</strong><button type="button" onClick={() => setMobilePanel(null)} className="min-h-11 rounded-xl border px-4">Cerrar</button></div><div className="max-h-[calc(88vh-65px)] overflow-auto">{mobilePanel === 'structure' ? <BuilderSidebar sections={state.sections} selected={state.selectedSection} onSelect={(section) => { dispatch({ type: 'SELECT', section }); setMobilePanel(null); }} onChange={changeSections} onPick={(section) => { pick(section); setMobilePanel(null); }} /> : <BuilderInspector business={state.business} selected={state.selectedSection} onChange={changeBusiness} />}</div></div></div>}
    {state.error && <p role="alert" className="fixed bottom-20 left-1/2 z-40 -translate-x-1/2 rounded-xl bg-red-700 px-4 py-3 text-sm text-white">{state.error}</p>}{publishError && <div role="alert" className="fixed inset-x-4 top-24 z-50 mx-auto max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><p>{publishError}</p><button type="button" onClick={() => setPublishError('')} className="mt-3 rounded-xl border px-3 py-2">Entendido</button></div>}</main>;
}



