import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { CDP, base, launchChrome, sleep } from './business-qa-client.mjs';
import { prepareQaUser, createQaBusiness, cleanupQaData } from './business-e2e-fixture.mjs';
import { PrismaClient } from '../backend/node_modules/@prisma/client/index.js';
import { encode } from '../backend/node_modules/@auth/core/jwt.js';
import dotenv from '../backend/node_modules/dotenv/lib/main.js';
dotenv.config({ path: new URL('../backend/.env', import.meta.url) });
const prisma = new PrismaClient();
const out = path.resolve('qa/business-captures/responsive-final');
const widths = [375,390,430,768,1024,1280,1440];
const pages = ['home','store','product','cart','checkout','dashboard','builder','business-public'];
let chrome, client, user, business;
const evaluate = async (expression) => (await client.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true})).result?.value;
const wait = async (expression, timeout=30000) => { const start=Date.now(); while(Date.now()-start<timeout){if(await evaluate(`Boolean(${expression})`)) return; await sleep(150);} throw new Error(`timeout ${expression}`); };
const metricsExpression = `(()=>{const els=[...document.querySelectorAll('body *')].filter(n=>{const s=getComputedStyle(n),r=n.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0});const rect=n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}};const outside=els.filter(n=>{if(n.closest('[aria-hidden="true"]'))return false;const r=n.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return false;let p=n.parentElement;while(p){const s=getComputedStyle(p);if((s.overflowX==='auto'||s.overflowX==='scroll')&&p.scrollWidth>p.clientWidth)return false;p=p.parentElement}return r.right>innerWidth+1||r.left<-1});const small=els.filter(n=>{const r=n.getBoundingClientRect();return r.top<innerHeight&&r.bottom>0&&(n.matches('button,a,input,select,textarea')||n.getAttribute('role')==='button')&&r.height<32});const images=[...document.images].map(i=>({alt:i.alt,broken:i.complete&&i.naturalWidth===0}));const text=document.body.innerText||'';return {url:location.href,title:document.title,scrollWidth:document.documentElement.scrollWidth,innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,outside:outside.slice(0,12).map(n=>({tag:n.tagName,text:(n.textContent||'').trim().slice(0,80),...rect(n)})),small:small.slice(0,12).map(n=>({tag:n.tagName,text:(n.textContent||'').trim().slice(0,50),...rect(n)})),brokenImages:images.filter(x=>x.broken),images:images.length,headings:document.querySelectorAll('h1,h2,h3').length,buttons:document.querySelectorAll('button,a').length,textLength:text.length,hasMain:!!document.querySelector('main'),hasHeader:!!document.querySelector('header'),hasFooter:!!document.querySelector('footer')}})()`;
async function capture(page,width){await client.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<768});let url=base+({home:'/',store:'/productos',product:'/productos',cart:'/carrito',checkout:'/checkout',dashboard:'/negocio',builder:`/negocio/editor?id=${business.id}`, 'business-public':'/__qa/business/flowers'}[page]);if(page==='product'){const data=await evaluate(`fetch('/api/products?limit=100').then(r=>r.json())`);const item=(data.products||data.items||data.data||[]).find(x=>x.slug);if(item)url=base+'/productos/'+item.slug;}await client.send('Page.navigate',{url});await sleep(page==='home'?2200:1800);if(page==='builder') await wait(`document.querySelector('[data-testid="business-builder"]')`);if(page==='dashboard') await wait(`document.body.innerText.includes('Mis páginas') || document.body.innerText.includes('Crear página web')`);const metrics=await evaluate(metricsExpression);const shot=await client.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});await writeFile(path.join(out,`${page}-${width}.png`),Buffer.from(shot.data,'base64'));return {page,width,url,metrics};}
try{await mkdir(out,{recursive:true});user=await prepareQaUser();business=await createQaBusiness(user.userId,{name:'QA Responsive Flowers',category:'FLOWERS'});await prisma.user.update({where:{id:user.userId},data:{role:'BUSINESS'}});const secret=process.env.AUTH_SECRET||process.env.NEXTAUTH_SECRET;const token=await encode({token:{id:user.userId,sub:user.userId,email:user.email,role:'BUSINESS'},secret,salt:'authjs.session-token'});const l=await launchChrome(process.cwd());chrome=l.chrome;client=new CDP(l.target.webSocketDebuggerUrl);await client.open();await Promise.all([client.send('Page.enable'),client.send('Runtime.enable'),client.send('Network.enable'),client.send('Log.enable')]);await client.send('Network.setCookie',{name:'authjs.session-token',value:token,url:base,path:'/',httpOnly:true,secure:false,sameSite:'Lax'});const report=[];for(const page of pages)for(const width of widths)report.push(await capture(page,width));const summary={generatedAt:new Date().toISOString(),widths,pass:report.every(x=>!x.metrics.overflow&&!x.metrics.outside.length&&!x.metrics.small.length&&!x.metrics.brokenImages.length),report};await writeFile(path.resolve('qa/responsive-final-report.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify({pass:summary.pass,pages:report.length,summary:widths.map(width=>({width,pass:report.filter(x=>x.width===width).every(x=>!x.metrics.overflow&&!x.metrics.outside.length&&!x.metrics.small.length&&!x.metrics.brokenImages.length)}))},null,2));if(!summary.pass)process.exitCode=1;}catch(e){console.error(e);process.exitCode=1}finally{client?.close();chrome?.kill();if(user)await cleanupQaData({userId:user.userId,businessId:business?.id}).catch(console.error);await prisma.$disconnect();}
